
@baseUrl = https://127.0.0.1:8000


# @name login
POST {{baseUrl}}/api/login_check
Content-Type: application/json

{
    "username": "admin",
    "password": "1234"
}

############################################
### JWT
############################################

@jwtToken = {{login.response.body.$.token}}
@refreshToken = {{login.response.body.$.refresh_token}}

###
POST {{baseUrl}}/token/refresh
Content-Type: application/json

{
    "refresh_token": "{{refreshToken}}"
}


###

GET {{baseUrl}}/api/produits
Authorization: Bearer {{jwtToken}}


###

GET {{baseUrl}}/api/produits
